version: '3'
services:
  log-mansion-nginx:
    container_name: "log-mansion-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - log-mansion-app
    ports:
      - 80:80
    volumes:
      - ./:/src
      - ./docker/nginx:/etc/nginx/conf.d

  log-mansion-app:
    container_name: "log-mansion-app"
    build:
      context: ./docker/php
    environment:
      DB_HOST: log-mansion-mysql
    depends_on:
      - log-mansion-mysql
    volumes:
      - ./:/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  log-mansion-mysql:
    image: mysql:8.0
    container_name: log-mansion-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      # - ./docker/mysql:/var/lib/mysql
      - ./docker/mysql/db/riclink_admin.sql:/docker-entrypoint-initdb.d/riclink_admin.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER= ${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Tokyo

    ports:
      - 3306:3306

  # log-mansion-redis:
  #   image: redis:alpine
  #   container_name: "log-mansion-redis"
  #   ports:
  #     - 16379:6379

  log-mansion-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: log-mansion-pma
    links:
      - log-mansion-mysql
    environment:
      PMA_HOST:  log-mansion-mysql
      MYSQL_ROOT_PASSWORD : root
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80
