name: logmansion_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  shared_preferences: ^2.2.3
  persistent_bottom_nav_bar_v2: ^5.2.3
  equatable: ^2.0.0
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/



  fonts:
     - family: Plus Jakarta Sans
       fonts:
         - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
         - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
